// <auto-generated />
using METS.Context.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace METS.Context.Migrations.Catalog
{
    [DbContext(typeof(CatalogContext))]
    partial class CatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("METS.Context.Catalog.AppAbsoluteSegmentViewModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Address");

                    b.Property<string>("ApplicationId");

                    b.Property<string>("Data");

                    b.Property<string>("Mask");

                    b.Property<int>("Size");

                    b.HasKey("Id");

                    b.ToTable("AppAbsoluteSegments");
                });

            modelBuilder.Entity("METS.Context.Catalog.AppComObject", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId")
                        .HasMaxLength(100);

                    b.Property<int>("Datapoint");

                    b.Property<int>("DatapointSub");

                    b.Property<bool>("Flag_Communicate");

                    b.Property<bool>("Flag_Read");

                    b.Property<bool>("Flag_ReadOnInit");

                    b.Property<bool>("Flag_Transmit");

                    b.Property<bool>("Flag_Update");

                    b.Property<bool>("Flag_Write");

                    b.Property<string>("FunctionText_DE")
                        .HasMaxLength(100);

                    b.Property<string>("FunctionText_EN")
                        .HasMaxLength(100);

                    b.Property<int>("Number");

                    b.Property<int>("Size");

                    b.Property<string>("Text_DE")
                        .HasMaxLength(100);

                    b.Property<string>("Text_EN")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("AppComObjects");
                });

            modelBuilder.Entity("METS.Context.Catalog.AppParameter", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AbsoluteSegmentId")
                        .HasMaxLength(100);

                    b.Property<int>("Access");

                    b.Property<string>("ApplicationId")
                        .HasMaxLength(100);

                    b.Property<int>("Offset");

                    b.Property<int>("OffsetBit");

                    b.Property<string>("ParameterTypeId")
                        .HasMaxLength(100);

                    b.Property<string>("Text");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("AppParameters");
                });

            modelBuilder.Entity("METS.Context.Catalog.AppParameterTypeEnumViewModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Order");

                    b.Property<string>("ParameterId")
                        .HasMaxLength(100);

                    b.Property<string>("Text")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("AppParameterTypeEnums");
                });

            modelBuilder.Entity("METS.Context.Catalog.AppParameterTypeViewModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Size");

                    b.Property<string>("Tag1")
                        .HasMaxLength(100);

                    b.Property<string>("Tag2")
                        .HasMaxLength(100);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("AppParameterTypes");
                });

            modelBuilder.Entity("METS.Context.Catalog.ApplicationViewModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Manufacturer");

                    b.Property<string>("Mask")
                        .HasMaxLength(7);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int>("Number");

                    b.Property<string>("Table_Assosiations")
                        .HasMaxLength(40);

                    b.Property<int>("Table_Assosiations_Max");

                    b.Property<int>("Table_Assosiations_Offset");

                    b.Property<string>("Table_Group")
                        .HasMaxLength(40);

                    b.Property<int>("Table_Group_Max");

                    b.Property<int>("Table_Group_Offset");

                    b.Property<string>("Table_Object")
                        .HasMaxLength(40);

                    b.Property<int>("Table_Object_Offset");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("METS.Context.Catalog.CatalogViewModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name_DE")
                        .HasMaxLength(100);

                    b.Property<string>("Name_EN")
                        .HasMaxLength(100);

                    b.Property<string>("ParentId")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("METS.Context.Catalog.DeviceViewModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusCurrent");

                    b.Property<string>("CatalogId")
                        .HasMaxLength(100);

                    b.Property<string>("HardwareId")
                        .HasMaxLength(100);

                    b.Property<bool>("HasApplicationProgram");

                    b.Property<bool>("HasIndividualAddress");

                    b.Property<bool>("IsCoupler");

                    b.Property<bool>("IsPowerSupply");

                    b.Property<bool>("IsRailMounted");

                    b.Property<string>("ManufacturerId")
                        .HasMaxLength(7);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(100);

                    b.Property<string>("VisibleDescription")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("METS.Context.Catalog.Hardware2AppModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId");

                    b.Property<string>("HardwareId");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int>("Number");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Hardware2App");
                });

            modelBuilder.Entity("METS.Context.Catalog.ManufacturerViewModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("KnxManufacturerId");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
