// <auto-generated />
using METS.Context.Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace METS.Context.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20191118150503_ComObjects")]
    partial class ComObjects
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("METS.Context.Project.ChangeParamModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DeviceId");

                    b.Property<string>("ParamId");

                    b.Property<int>("StateId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("ChangesParam");
                });

            modelBuilder.Entity("METS.Context.Project.LineDeviceModel", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationId");

                    b.Property<string>("ComObjects");

                    b.Property<string>("DeviceId");

                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.Property<int>("ParentId");

                    b.Property<int>("ProjectId");

                    b.HasKey("UId");

                    b.ToTable("LineDevices");
                });

            modelBuilder.Entity("METS.Context.Project.LineMiddleModel", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Id");

                    b.Property<bool>("IsExpanded");

                    b.Property<string>("Name");

                    b.Property<int>("ParentId");

                    b.Property<int>("ProjectId");

                    b.HasKey("UId");

                    b.ToTable("LinesMiddle");
                });

            modelBuilder.Entity("METS.Context.Project.LineModel", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Id");

                    b.Property<bool>("IsExpanded");

                    b.Property<string>("Name");

                    b.Property<int>("ProjectId");

                    b.HasKey("UId");

                    b.ToTable("LinesMain");
                });

            modelBuilder.Entity("METS.Context.Project.ProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("METS.Context.Project.StateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("ProjectId");

                    b.HasKey("Id");

                    b.ToTable("States");
                });
#pragma warning restore 612, 618
        }
    }
}
